#!/bin/sh

case $1 in

	# new
	n)
		printf "post title: "
		read title

		if [ -z $2 ]; then
			touch "`date +'%Y-%m-%d'`-$title.md"
		else
			mkdir -p $2
			touch "$2/`date +'%Y-%m-%d'`-$title.md"
		fi

		echo "created '$title'"
		;;

	# clean
	c)
		echo "cleaning junk..."
		find . -type f -name "**.html" -delete
		;;

	# compile
	*)
		echo "compiling posts..."
		find . -type f -name "**.md" -exec bash -c\
			'for f in "$@"; do\
				marked $f -o ${f/%md/html};\
				cat meta.template ${f/%md/html} > .tmp;\
				mv .tmp ${f/%md/html};\
			done' {} +
		;;

esac
